var elements = document.getElementsByTagName('*');

var wordPairs = {
	acceptable: "alright",
	action: "doing",
	active: "busy",
	activist: "cause furtherer",
	adblockers: "people who block the business pictures",
	adblocking: "business picture blocking",
	ad: "business picture",
	ads: "business pictures",
	africa: "second biggest home land in the world",
	alive: "not dead",
	america: "land of gun",
	americas: "land of guns",
	april: "month four",
	argue: "fight",
	asia: "biggest home land in the world",
	assisted: "helped",
	bean: "bit",
	beans: "bits",
	berries: "nice good for you foods",
	berry: "nice good for you food",
	brewed: "put in hot water",
	brew: "put in hot water",
	british: "world taking over people",
	brotherhood: "group of brothers",
	cat: "dog",
	categorized: "classed",
	category: "class",
	choice: "pick",
	coffea: "strange other home land",
	committee: "group of people",
	commonly: "often",
	common: "often",
	consent: "okay",
	cost: "take money from",
	council: "decision people",
	countries: "areas of people with the same tongue",
	country: "area of people with the same tongue",
	cultivated: "picked up",
	cultivate: "pick up",
	define: "call",
	defines: "calls",
	definite: "clear",
	deliberate: "definite",
	deliberately: "definitely",
	described: "explained",
	differences: "changes",
	discussing: "talking about",
	disease: "bad form",
	diseases: "bad forms",
	display: "show",
	dog: "hitler",
	drug: "good food",
	easter: "god's son living again day",
	engaged: "got into",
	england: "world taking over area of people with the same tongue",
	equatorial: "warm middle",
	establish: "make",
	ethics: "business",
	euthanasia: "nice death",
	example: "case",
	examples: "cases",
	exported: "sent away",
	express: "say",
	generally: "usually",
	gradually: "slowly",
	heavily: "strongly",
	highly: "much",
	illegal: "not allowed",
	ill: "sick",
	include: "have",
	independent: "on their own",
	india: "hot mouth hurt food place",
	injection: "hit",
	install: "use",
	insurrection: "fight",
	intentionally: "planned",
	intention: "plan",
	intent: "plan",
	intervention: "getting in the middle",
	intractable: "really bad",
	intrusive: "bad",
	involuntary: "not wanted by the person",
	involve: "has",
	involves: "has",
	ireland: "green people country",
	irish: "small green country",
	island: " small land in the big water",
	islands: "small lands in the big water",
	kingdom: "big man at the top country",
	launched: "started doing",
	law: "control",
	laws: "controls",
	legal: "allowed",
	lord: "big man",
	lords: "big men",
	measure: "look at",
	medical: "doctor",
	military: "fighting people",
	monday: "day one of the week",
	murder: "other person kill",
	native: "home",
	non: "not",
	occur: "happen",
	occurs: "happens",
	organised: "did",
	painless: "soft hurt",
	passive: "calm",
	patient: "sick person",
	pill: "small good food bits",
	plant: "green thing from the ground",
	plants: "green things from the ground",
	prepared: "made ready",
	primarily: "especially",
	provide: "give",
	providing: "giving",
	rebellion: "fighting against",
	regarded: "looked at",
	region: "area",
	regions: "areas",
	regulate: "control",
	regulated: "controlled",
	relieve: "excuse",
	remove: "take away",
	removing: "taking away",
	republicans: "people who want people-decided power",
	republic: "country where the people choose the leader",
	request: "ask for",
	result: "lead",
	revenue: "money",
	roasted: "making hot until nice",
	roast: "heat until nice",
	rule: "law making",
	schoolmaster: "big school man",
	seed: "children",
	seeds: "children",
	seized: "took",
	separated: "put alone",
	significant: "really big",
	southeast: "down right",
	southern: "down",
	specifically: "definitely",
	subtropical: "warm",
	suffer: "hurt",
	suffering: "hurting",
	suicide: "self death",
	support: "hold up",
	supporting: "holding up",
	tailored: "specially made",
	terminally: "lost",
	terminal: "stop",
	termination: "ending",
	thousands: "tens of hundreds",
	thousand: "ten hundred",
	tight: "close",
	tightly: "closely",
	treatment: "care",
	undertake: "approach",
	united: "together",
	unlock: "open up",
	uprising: "big fight",
	ventilator: "breathing help",
	voluntary: "wanted by the person",
	volunteers: "people who work for free",
	website: "computer page",
	websites: "computer pages",
};

var re = new RegExp(Object.keys(wordPairs).join('|'), 'gi');

function explainify(word){
	var candidate = wordPairs[word.toLowerCase().trim()];
	return (candidate === null || candidate === undefined ? word : candidate);

}

for (var i = 0; i < elements.length; i++) {
	var element = elements[i];

	for (var j = 0; j < element.childNodes.length; j++) {
		var node = element.childNodes[j];

		if (node.nodeType === 3) {
			var text = node.nodeValue;
			var str = text.replace(/\b[a-zA-Z]+?\b/gi, explainify);
			if (str !== text) {
				element.replaceChild(document.createTextNode(str), node);
			}
		}
	}
}
